image: microsoft/dotnet:latest

stages:
  - build
  - test

variables:
  AZUREBLOB_CONTAINER: testblob
  AZUREBLOB_ACCOUNT_NAME: devstoreaccount1
  AZUREBLOB_ACCOUNT_KEY: Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
  AZUREBLOB_HOST: http://azureblob:10000/devstoreaccount1

before_script:
  - dotnet restore -s https://www.myget.org/F/s2/ -s https://api.nuget.org/v3/index.json

build:
  stage: build
  script:
    - dotnet build

test:
  stage: test
  services:
    - name: itsplus/s2shape-azureblob-test
      alias: azureblob

  script:
    - dotnet build
    - dotnet test
