image: itsplus/s2shape-test-harness

stages:
  - build
  - test

variables:
  AZUREBLOB_CONTAINER: testblob
  AZUREBLOB_ACCOUNT_NAME: devstoreaccount1
  AZUREBLOB_ACCOUNT_KEY: Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
  AZUREBLOB_HOST: http://azureblob:10000/$AZUREBLOB_ACCOUNT_NAME

before_script:
  - dotnet restore -s https://www.myget.org/F/s2/ -s https://api.nuget.org/v3/index.json

build:
  stage: build
  script:
    - dotnet build

test:
  stage: test
  services:
    - name: mcr.microsoft.com/azure-storage/azurite
      alias: azureblob

  script:
    - ROOT_PROJECT_PATH=$(pwd)
    - dotnet build
    - dotnet publish
    - cd $ROOT_PROJECT_PATH/AzureBlobSupplyCollectorLoader/bin/Debug/netcoreapp2.2/publish
    - cp -f /SupplyCollectorDataLoader/SupplyCollectorDataLoader/bin/Debug/netcoreapp2.2/SupplyCollectorDataLoader.runtimeconfig.json .
    - dotnet SupplyCollectorDataLoader.dll -init AzureBlobSupplyCollector azureblob://$AZUREBLOB_ACCOUNT_NAME:$AZUREBLOB_ACCOUNT_KEY/$AZUREBLOB_CONTAINER,override_host=$AZUREBLOB_HOST
    - dotnet SupplyCollectorDataLoader.dll -xunit AzureBlobSupplyCollector azureblob://$AZUREBLOB_ACCOUNT_NAME:$AZUREBLOB_ACCOUNT_KEY/$AZUREBLOB_CONTAINER,override_host=$AZUREBLOB_HOST
    - cd $ROOT_PROJECT_PATH
    - dotnet test

load_test:
  stage: test
  services:
    - name: mcr.microsoft.com/azure-storage/azurite
      alias: azureblob

  script:
    - ROOT_PROJECT_PATH=$(pwd)
    - dotnet build
    - dotnet publish
    - cd $ROOT_PROJECT_PATH/AzureBlobSupplyCollectorLoader/bin/Debug/netcoreapp2.2/publish
    - cp -f /SupplyCollectorDataLoader/SupplyCollectorDataLoader/bin/Debug/netcoreapp2.2/SupplyCollectorDataLoader.runtimeconfig.json .
    - dotnet SupplyCollectorDataLoader.dll -init AzureBlobSupplyCollector azureblob://$AZUREBLOB_ACCOUNT_NAME:$AZUREBLOB_ACCOUNT_KEY/$AZUREBLOB_CONTAINER,override_host=$AZUREBLOB_HOST
    - dotnet SupplyCollectorDataLoader.dll -xunit AzureBlobSupplyCollector azureblob://$AZUREBLOB_ACCOUNT_NAME:$AZUREBLOB_ACCOUNT_KEY/$AZUREBLOB_CONTAINER,override_host=$AZUREBLOB_HOST
    - dotnet SupplyCollectorDataLoader.dll -samples AzureBlobSupplyCollector azureblob://$AZUREBLOB_ACCOUNT_NAME:$AZUREBLOB_ACCOUNT_KEY/$AZUREBLOB_CONTAINER,override_host=$AZUREBLOB_HOST TestCollection Test1:int,Test2:string,Test3:bool,Test4:double,Test5 1000000
    - cd $ROOT_PROJECT_PATH/AzureBlobSupplyCollectorTests/bin/Debug/netcoreapp2.2/publish
    - SupplyCollectorTestHarness

